// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessPensionMicroservice.Data;

namespace ProcessPensionMicroservice.Migrations
{
    [DbContext(typeof(MThreePensionDbContext))]
    partial class MThreePensionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProcessPensionMicroservice.Models.PensionDetail", b =>
                {
                    b.Property<long>("aadharno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BankServiceCharge")
                        .HasColumnType("bigint");

                    b.Property<long>("PensionAmount")
                        .HasColumnType("bigint");

                    b.HasKey("aadharno");

                    b.ToTable("pensionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
